var MARATHON_META = [
    {
        id:          "pittsburgh",
        title:       "Pittsburgh Marathon",
        location:    "Pittsburgh, PA",
        years:       ["2018", "2019"],
        bestTime:    "2:53:53",
        gain:        "933ft",
        description: "My first marathon! My home city! A beautiful way to first tackle 26.2 miles. <br><br>Of all the races I've ever run, I still think this course is the most exciting - there is almost no 'dead' area, the crowds are energetic the whole way, and the route makes you appreciate the character of all the Pittsburgh neighborhoods.<br><br>I didn't know how to train for a marathon in 2018 (other than 'run a lot'), so my first-ever marathon time of 3:09:46 wasn't too bad! A year later, I worked out a better training strategy and got a BQ.",
    },
    {
        id:          "philadelphia",
        title:       "Philadelphia Marathon",
        location:    "Philadelphia, PA",
        years:       ["2018", "2019", "2021", "2022"],
        bestTime:    "2:53:04",
        gain:        "651ft",
        description: "Philly is my favorite marathon - my comfort food of marathons. It's where I learned how to run a marathon properly. I've ran it more than any other race.<br><br>In 2018, my buddy in college wanted to run his first marathon and we spent months training for this one, and it was the first time I qualified for Boston. Since then, I've done it two other times on this course.<br><br>The reason I keep coming back to this one is nostalgic at this point - it's the Sunday before Thanksgiving, usually bitter cold in November and a few days before my birthday. I take an Amtrak across Pennsylvania and stay at my sister's place and get my business done. The course is challenging but fast, the crowds are energetic, and everyone's excited for the holidays and ready to eat a huge turkey dinner a few days later.<br><br>There's so much to love about the energy here, and the finish line is a great place to grab a free hot dog and take a pic in front of the Rocky Balboa statue.",
    },
    {
        id:          "berlin",
        title:       "Berlin Marathon",
        location:    "Berlin, Germany",
        years:       ["2021"],
        bestTime:    "3:05:10",
        gain:        "246ft",
        description: "Berlin - my first Marathon Major!<br><br>This race was electric! I won a lottery placement with three friends from college, and we took a flight over to Germany to knock an Abbott race off our list. <br><br>Running nerds know this course is one of the fastest of the fastest. I did not run my fastest - I was there as a tourist runner - and I had a great time. <br><br>There's so much I love about my experience in this race. It's exciting to land at the airport on a different continent, see people from all over the world doing warmup jogs throughout the city, pick up bibs at Tempelhof, and then shred through the streets with huge crowds everywhere. <br><br>The year I ran was unfortunately considered an election interference (lookup how much chaos the marathon route caused on an election day!). Oktoberfest was canceled due to Covid, but it's tradition for runners to hop on an ICE after the race and head to my beloved home-away-from-home city, Munich. My parents joined on this trip. We did a 2-week tour of a few countries since it was my dad's first time in Europe.",
    },
    {
        id:          "chicago",
        title:       "Chicago Marathon",
        location:    "Chicago, IL",
        years:       ["2022"],
        bestTime:    "3:XX:XX",
        gain:        "243ft",
        description: "The Chicago Marathon was such a treat. Of all my races, it's the one I want to repeat the most. The course is flat and slick and the place I hit my PR (first and only NYC qualifier!) in perfect October weather, on a sunny Sunday morning along the Lake Michigan lakefront, with my brother and parents in the crowd. Afterwards, I squeezed in deep dish pizza and a visit to the Art Institute of Chicago before the roadtrip home. <br><br>To me, the Chicago Marathon is the gold standard for a well-run event with energetic crowds and great atmosphere.",
    },
    {
        id:          "boston",
        title:       "Boston Marathon",
        location:    "Boston, MA",
        years:       ["2023"],
        bestTime:    "3:XX:XX",
        gain:        "906ft",
        description: "What is there to say about the Boston Marathon? There's nothing else like it. It's the dream for any distance runner to qualify and join the starting line in Hopkinton. <br><br>I was lucky enough to race in 2023, and it's one of those experience that makes you feel like you 'made it' as a runner. Not my fastest time (there were downpours at the end and I was fully waterlogged at the finish), but I was there for the joy of it all. <br><br>Early in the morning, you ship out in a bus from Boston Common for the point-to-point course's starting line. It's a community event - you meet other runners from all over the world and fight for port-a-johns in a muddy high school field before walking a half mile to begin the race. <br><br>The course itself runs through quiet roads and opens up to louder and louder crowds (Wellesly particularly!), climbs up a couple brutal hills, and finishes in the Back Bay neighborhood.",
    },
    {
        id:          "salzburg",
        title:       "Salzburg Marathon",
        location:    "Salzburg, Austria",
        years:       ["2024"],
        bestTime:    "3:XX:XX",
        gain:        "194ft",
        description: "Salzburg is a beautiful city and just a short train ride from Munich, where I was living during the year that I ran this marathon. I signed up for this race with a friend who was running 26.2 for the very first time, and training was limited to about 4-5 weeks total. <br><br>The race event was relatively small and the crowd of runners was one of the smallest I'd been a part of. The course is relatively flat and covers two loops that weave around the old city, through tree-lined country roads, and past the lake house from the Sound of Music. Beautiful way to spend a weekend!",
    },
    {
        id:          "rotorua",
        title:       "Rotorua Marathon",
        location:    "Rotorua, New Zealand",
        years:       ["2025"],
        bestTime:    "3:03:56",
        gain:        "827ft",
        description: "My first (and only!) race in the Southern Hemisphere. <br><br>Rotorua is New Zealand's oldest marathon, and the event happened to be held smack in the middle of my two-month backpacking trip in the country. <br><br>It's a rolling course that follows the rim of a volcanic lake and starts/ends in Rotorua, a tourist town that stinks of sulfur from all the geothermal springs. For such an iconic race I was surprised how small the crowd seemed!<br><br>I didn't train much for this one - just a few weeks of prep - and so I was delighted with my finishing time. Afterwards I took a drive out to the geothermally heated Kerosene Creek to relax my muscles.",
    }
];
